/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProRouteImport } from './routes/pro'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HubRouteImport } from './routes/hub'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as MarketplaceListRouteImport } from './routes/marketplace.list'
import { Route as MarketplaceAssetIdRouteImport } from './routes/marketplace.$assetId'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalCreatorAgreementRouteImport } from './routes/legal.creator-agreement'
import { Route as GSlugRouteImport } from './routes/g.$slug'
import { Route as CollectionsCollectionIdRouteImport } from './routes/collections.$collectionId'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceListRoute = MarketplaceListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceAssetIdRoute = MarketplaceAssetIdRouteImport.update({
  id: '/$assetId',
  path: '/$assetId',
  getParentRoute: () => MarketplaceRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCreatorAgreementRoute = LegalCreatorAgreementRouteImport.update({
  id: '/creator-agreement',
  path: '/creator-agreement',
  getParentRoute: () => LegalRoute,
} as any)
const GSlugRoute = GSlugRouteImport.update({
  id: '/g/$slug',
  path: '/g/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdRoute = CollectionsCollectionIdRouteImport.update({
  id: '/$collectionId',
  path: '/$collectionId',
  getParentRoute: () => CollectionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/builder': typeof BuilderRoute
  '/changelog': typeof ChangelogRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/hub': typeof HubRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/moderation': typeof ModerationRoute
  '/notifications': typeof NotificationsRoute
  '/pro': typeof ProRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/wallet': typeof WalletRoute
  '/wishlist': typeof WishlistRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/g/$slug': typeof GSlugRoute
  '/legal/creator-agreement': typeof LegalCreatorAgreementRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/marketplace/$assetId': typeof MarketplaceAssetIdRoute
  '/marketplace/list': typeof MarketplaceListRoute
  '/u/$handle': typeof UHandleRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/builder': typeof BuilderRoute
  '/changelog': typeof ChangelogRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/hub': typeof HubRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/moderation': typeof ModerationRoute
  '/notifications': typeof NotificationsRoute
  '/pro': typeof ProRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/wallet': typeof WalletRoute
  '/wishlist': typeof WishlistRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/g/$slug': typeof GSlugRoute
  '/legal/creator-agreement': typeof LegalCreatorAgreementRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/marketplace/$assetId': typeof MarketplaceAssetIdRoute
  '/marketplace/list': typeof MarketplaceListRoute
  '/u/$handle': typeof UHandleRoute
  '/marketplace': typeof MarketplaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/builder': typeof BuilderRoute
  '/changelog': typeof ChangelogRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/hub': typeof HubRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/moderation': typeof ModerationRoute
  '/notifications': typeof NotificationsRoute
  '/pro': typeof ProRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/wallet': typeof WalletRoute
  '/wishlist': typeof WishlistRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/g/$slug': typeof GSlugRoute
  '/legal/creator-agreement': typeof LegalCreatorAgreementRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/marketplace/$assetId': typeof MarketplaceAssetIdRoute
  '/marketplace/list': typeof MarketplaceListRoute
  '/u/$handle': typeof UHandleRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/builder'
    | '/changelog'
    | '/collections'
    | '/create'
    | '/dashboard'
    | '/feed'
    | '/hub'
    | '/legal'
    | '/login'
    | '/marketplace'
    | '/moderation'
    | '/notifications'
    | '/pro'
    | '/profile'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/templates'
    | '/wallet'
    | '/wishlist'
    | '/collections/$collectionId'
    | '/g/$slug'
    | '/legal/creator-agreement'
    | '/legal/privacy'
    | '/legal/terms'
    | '/marketplace/$assetId'
    | '/marketplace/list'
    | '/u/$handle'
    | '/marketplace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/builder'
    | '/changelog'
    | '/collections'
    | '/create'
    | '/dashboard'
    | '/feed'
    | '/hub'
    | '/legal'
    | '/login'
    | '/moderation'
    | '/notifications'
    | '/pro'
    | '/profile'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/templates'
    | '/wallet'
    | '/wishlist'
    | '/collections/$collectionId'
    | '/g/$slug'
    | '/legal/creator-agreement'
    | '/legal/privacy'
    | '/legal/terms'
    | '/marketplace/$assetId'
    | '/marketplace/list'
    | '/u/$handle'
    | '/marketplace'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/builder'
    | '/changelog'
    | '/collections'
    | '/create'
    | '/dashboard'
    | '/feed'
    | '/hub'
    | '/legal'
    | '/login'
    | '/marketplace'
    | '/moderation'
    | '/notifications'
    | '/pro'
    | '/profile'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/templates'
    | '/wallet'
    | '/wishlist'
    | '/collections/$collectionId'
    | '/g/$slug'
    | '/legal/creator-agreement'
    | '/legal/privacy'
    | '/legal/terms'
    | '/marketplace/$assetId'
    | '/marketplace/list'
    | '/u/$handle'
    | '/marketplace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BuilderRoute: typeof BuilderRoute
  ChangelogRoute: typeof ChangelogRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  FeedRoute: typeof FeedRoute
  HubRoute: typeof HubRoute
  LegalRoute: typeof LegalRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  ModerationRoute: typeof ModerationRoute
  NotificationsRoute: typeof NotificationsRoute
  ProRoute: typeof ProRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TemplatesRoute: typeof TemplatesRoute
  WalletRoute: typeof WalletRoute
  WishlistRoute: typeof WishlistRoute
  GSlugRoute: typeof GSlugRoute
  UHandleRoute: typeof UHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/list': {
      id: '/marketplace/list'
      path: '/list'
      fullPath: '/marketplace/list'
      preLoaderRoute: typeof MarketplaceListRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/$assetId': {
      id: '/marketplace/$assetId'
      path: '/$assetId'
      fullPath: '/marketplace/$assetId'
      preLoaderRoute: typeof MarketplaceAssetIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/creator-agreement': {
      id: '/legal/creator-agreement'
      path: '/creator-agreement'
      fullPath: '/legal/creator-agreement'
      preLoaderRoute: typeof LegalCreatorAgreementRouteImport
      parentRoute: typeof LegalRoute
    }
    '/g/$slug': {
      id: '/g/$slug'
      path: '/g/$slug'
      fullPath: '/g/$slug'
      preLoaderRoute: typeof GSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsCollectionIdRoute: typeof CollectionsCollectionIdRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsCollectionIdRoute: CollectionsCollectionIdRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface LegalRouteChildren {
  LegalCreatorAgreementRoute: typeof LegalCreatorAgreementRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalCreatorAgreementRoute: LegalCreatorAgreementRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface MarketplaceRouteChildren {
  MarketplaceAssetIdRoute: typeof MarketplaceAssetIdRoute
  MarketplaceListRoute: typeof MarketplaceListRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceAssetIdRoute: MarketplaceAssetIdRoute,
  MarketplaceListRoute: MarketplaceListRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BuilderRoute: BuilderRoute,
  ChangelogRoute: ChangelogRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  FeedRoute: FeedRoute,
  HubRoute: HubRoute,
  LegalRoute: LegalRouteWithChildren,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  ModerationRoute: ModerationRoute,
  NotificationsRoute: NotificationsRoute,
  ProRoute: ProRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TemplatesRoute: TemplatesRoute,
  WalletRoute: WalletRoute,
  WishlistRoute: WishlistRoute,
  GSlugRoute: GSlugRoute,
  UHandleRoute: UHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
